<?php
/** AUTOMATISCH ERZEUGT aus themes/core/options.json (php bin/build-themes.php). Nicht von Hand ändern. */

return [
    'version' => '0.2.0',
    'groups' => [
        'colors' => [
            'label' => 'Farben',
            'help' => 'Akzentfarbe, Modus und eigene Farben',
        ],
        'typography' => [
            'label' => 'Schriften',
            'help' => 'Lokale Schriften und Größen',
        ],
        'shape' => [
            'label' => 'Form und Stil',
            'help' => 'Ecken, Abstände, Schatten, Buttons',
        ],
        'logo' => [
            'label' => 'Logo',
            'help' => 'Logo, Favicon, Größe',
        ],
        'header' => [
            'label' => 'Header',
            'help' => 'Kopfbereich und Suche',
        ],
        'footer' => [
            'label' => 'Footer',
            'help' => 'Fußbereich',
        ],
        'hero' => [
            'label' => 'Startseite',
            'help' => 'Hero-Bereich',
        ],
        'listing' => [
            'label' => 'Kategorie und Listing',
            'help' => 'Produktlisten',
        ],
        'detail' => [
            'label' => 'Artikelseite',
            'help' => 'Produkt-Detailseite',
        ],
        'legal' => [
            'label' => 'Recht',
            'help' => 'Preisangaben und Pflichttexte',
        ],
        'a11y' => [
            'label' => 'Barrierefreiheit',
            'help' => 'Fokus, Textgröße, Bewegung',
        ],
        'performance' => [
            'label' => 'Geschwindigkeit',
            'help' => 'Ladezeit',
        ],
        'advanced' => [
            'label' => 'Erweitert',
            'help' => 'Eigener Code (Pro)',
        ],
    ],
    'options' => [
        'color_mode' => [
            'key' => 'mt-color-mode',
            'group' => 'colors',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Farbmodus',
            'help' => 'Hell, Dunkel oder dem Gerät folgen. Besucher können im Shop umschalten.',
            'default' => 'system',
            'attr' => 'data-theme',
            'choices' => [
                'system' => 'Wie das Gerät',
                'light' => 'Hell',
                'dark' => 'Dunkel',
            ],
        ],
        'accent' => [
            'key' => 'mt-accent',
            'group' => 'colors',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Akzentfarbe',
            'help' => 'Farbe für Buttons, Links und Hervorhebungen. Alle Varianten sind für Hell und Dunkel auf Kontrast geprüft.',
            'default' => 'indigo',
            'attr' => 'data-accent',
            'choices' => [
                'teal' => 'Petrol',
                'indigo' => 'Indigo',
                'amber' => 'Bernstein',
                'rose' => 'Rose',
                'graphite' => 'Graphit',
            ],
        ],
        'accent_custom' => [
            'key' => 'mt-accent-custom',
            'group' => 'colors',
            'type' => 'color',
            'mode' => 'expert',
            'label' => 'Eigene Akzentfarbe',
            'help' => 'Leer lassen, um die Akzentfarbe von oben zu nutzen. Achtung: Eigene Farben werden nicht automatisch auf Kontrast geprüft.',
            'default' => '',
            'css' => '--mt-accent-custom',
        ],
        'mode_toggle' => [
            'key' => 'mt-mode-toggle',
            'group' => 'colors',
            'type' => 'toggle',
            'mode' => 'simple',
            'label' => 'Umschalter Hell/Dunkel im Header anzeigen',
            'help' => '',
            'default' => true,
        ],
        'font_body' => [
            'key' => 'mt-font-body',
            'group' => 'typography',
            'type' => 'font',
            'mode' => 'simple',
            'label' => 'Schrift für Text',
            'help' => 'Alle Schriften liegen lokal im Theme, es gibt keinen Abruf bei Google.',
            'default' => 'inter',
            'attr' => 'data-mt-font-body',
            'choices' => [
                'system' => 'Systemschrift (Arial/Helvetica)',
                'roboto' => 'Roboto',
                'open-sans' => 'Open Sans',
                'inter' => 'Inter',
                'lato' => 'Lato',
                'montserrat' => 'Montserrat',
                'source-sans-3' => 'Source Sans 3',
                'nunito' => 'Nunito',
                'merriweather' => 'Merriweather',
                'playfair-display' => 'Playfair Display',
            ],
        ],
        'font_heading' => [
            'key' => 'mt-font-heading',
            'group' => 'typography',
            'type' => 'font',
            'mode' => 'simple',
            'label' => 'Schrift für Überschriften',
            'help' => '',
            'default' => 'inter',
            'attr' => 'data-mt-font-heading',
            'choices' => [
                'system' => 'Systemschrift (Arial/Helvetica)',
                'roboto' => 'Roboto',
                'open-sans' => 'Open Sans',
                'inter' => 'Inter',
                'lato' => 'Lato',
                'montserrat' => 'Montserrat',
                'source-sans-3' => 'Source Sans 3',
                'nunito' => 'Nunito',
                'merriweather' => 'Merriweather',
                'playfair-display' => 'Playfair Display',
            ],
        ],
        'font_size' => [
            'key' => 'mt-font-size',
            'group' => 'typography',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Schriftgröße',
            'help' => '',
            'default' => 'normal',
            'attr' => 'data-mt-size',
            'choices' => [
                'small' => 'Klein',
                'normal' => 'Normal',
                'large' => 'Groß',
            ],
        ],
        'radius' => [
            'key' => 'mt-radius',
            'group' => 'shape',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Ecken',
            'help' => 'Rundung von Karten, Buttons und Bildern.',
            'default' => 'soft',
            'attr' => 'data-mt-radius',
            'choices' => [
                'sharp' => 'Eckig',
                'soft' => 'Leicht gerundet',
                'round' => 'Stark gerundet',
            ],
        ],
        'density' => [
            'key' => 'mt-density',
            'group' => 'shape',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Abstände',
            'help' => '',
            'default' => 'normal',
            'attr' => 'data-mt-density',
            'choices' => [
                'compact' => 'Kompakt',
                'normal' => 'Normal',
                'airy' => 'Luftig',
            ],
        ],
        'shadows' => [
            'key' => 'mt-shadows',
            'group' => 'shape',
            'type' => 'select',
            'mode' => 'expert',
            'label' => 'Schatten',
            'help' => '',
            'default' => 'soft',
            'attr' => 'data-mt-shadow',
            'choices' => [
                'none' => 'Keine',
                'soft' => 'Weich',
                'strong' => 'Kräftig',
            ],
        ],
        'buttons' => [
            'key' => 'mt-buttons',
            'group' => 'shape',
            'type' => 'select',
            'mode' => 'expert',
            'label' => 'Button-Stil',
            'help' => '',
            'default' => 'solid',
            'attr' => 'data-mt-buttons',
            'choices' => [
                'solid' => 'Gefüllt',
                'outline' => 'Umrandet',
                'pill' => 'Pillenform',
            ],
        ],
        'logo_light' => [
            'key' => 'mt-logo-light',
            'group' => 'logo',
            'type' => 'media',
            'mode' => 'simple',
            'label' => 'Logo (heller Hintergrund)',
            'help' => 'SVG oder PNG, mindestens doppelte Größe für scharfe Darstellung.',
            'default' => '',
        ],
        'logo_dark' => [
            'key' => 'mt-logo-dark',
            'group' => 'logo',
            'type' => 'media',
            'mode' => 'simple',
            'label' => 'Logo (dunkler Hintergrund)',
            'help' => 'Optional. Ohne Angabe wird das helle Logo genutzt.',
            'default' => '',
        ],
        'logo_alt' => [
            'key' => 'mt-logo-alt',
            'group' => 'logo',
            'type' => 'text',
            'mode' => 'simple',
            'label' => 'Alternativtext des Logos',
            'help' => 'Wird von Screenreadern vorgelesen. Meist der Shopname.',
            'default' => '',
        ],
        'logo_height' => [
            'key' => 'mt-logo-height',
            'group' => 'logo',
            'type' => 'range',
            'mode' => 'simple',
            'label' => 'Logohöhe in Pixel',
            'help' => '',
            'default' => 40,
            'css' => '--mt-logo-height',
            'unit' => 'px',
            'min' => 24,
            'max' => 96,
            'step' => 2,
        ],
        'favicon' => [
            'key' => 'mt-favicon',
            'group' => 'logo',
            'type' => 'media',
            'mode' => 'expert',
            'label' => 'Favicon',
            'help' => '',
            'default' => '',
        ],
        'header_layout' => [
            'key' => 'mt-header-layout',
            'group' => 'header',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Header-Layout',
            'help' => 'Aufbau des Kopfbereichs.',
            'default' => 'classic',
            'attr' => 'data-mt-header',
            'choices' => [
                'classic' => 'Klassisch (Logo links)',
                'centered' => 'Zentriert (Logo mittig)',
                'compact' => 'Kompakt (eine Zeile)',
            ],
        ],
        'header_sticky' => [
            'key' => 'mt-header-sticky',
            'group' => 'header',
            'type' => 'toggle',
            'mode' => 'simple',
            'label' => 'Header beim Scrollen fixieren',
            'help' => '',
            'default' => true,
            'attr' => 'data-mt-sticky',
        ],
        'header_search' => [
            'key' => 'mt-header-search',
            'group' => 'header',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Suche',
            'help' => '',
            'default' => 'field',
            'attr' => 'data-mt-search',
            'choices' => [
                'icon' => 'Nur Symbol',
                'field' => 'Suchfeld',
                'expanded' => 'Großes Suchfeld',
            ],
        ],
        'announcement' => [
            'key' => 'mt-announcement',
            'group' => 'header',
            'type' => 'toggle',
            'mode' => 'simple',
            'label' => 'Ankündigungsleiste anzeigen',
            'help' => '',
            'default' => false,
            'attr' => 'data-mt-announcement',
        ],
        'announcement_text' => [
            'key' => 'mt-announcement-text',
            'group' => 'header',
            'type' => 'text',
            'mode' => 'simple',
            'label' => 'Text der Ankündigungsleiste',
            'help' => 'Bitte nur belegbare Aussagen verwenden (UWG).',
            'default' => 'Kostenloser Versand ab 50 €',
        ],
        'footer_layout' => [
            'key' => 'mt-footer-layout',
            'group' => 'footer',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Footer-Layout',
            'help' => '',
            'default' => 'columns',
            'attr' => 'data-mt-footer',
            'choices' => [
                'columns' => 'Mehrspaltig',
                'centered' => 'Zentriert',
                'minimal' => 'Minimal',
            ],
        ],
        'footer_payment' => [
            'key' => 'mt-footer-payment',
            'group' => 'footer',
            'type' => 'toggle',
            'mode' => 'simple',
            'label' => 'Zahlungsarten im Footer zeigen',
            'help' => '',
            'default' => true,
        ],
        'footer_trust' => [
            'key' => 'mt-footer-trust',
            'group' => 'footer',
            'type' => 'toggle',
            'mode' => 'simple',
            'label' => 'Vertrauens-Hinweise zeigen',
            'help' => 'Zum Beispiel Rückgabe, Versand, Support. Nur Aussagen eintragen, die stimmen.',
            'default' => true,
        ],
        'trust_1' => [
            'key' => 'mt-trust-1',
            'group' => 'footer',
            'type' => 'text',
            'mode' => 'simple',
            'label' => 'Vertrauens-Hinweis 1',
            'help' => 'Nur eintragen, was im Shop tatsächlich gilt.',
            'default' => '',
        ],
        'trust_2' => [
            'key' => 'mt-trust-2',
            'group' => 'footer',
            'type' => 'text',
            'mode' => 'simple',
            'label' => 'Vertrauens-Hinweis 2',
            'help' => '',
            'default' => '',
        ],
        'trust_3' => [
            'key' => 'mt-trust-3',
            'group' => 'footer',
            'type' => 'text',
            'mode' => 'simple',
            'label' => 'Vertrauens-Hinweis 3',
            'help' => '',
            'default' => '',
        ],
        'hero_style' => [
            'key' => 'mt-hero-style',
            'group' => 'hero',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Hero-Bereich',
            'help' => 'Großer Einstieg auf der Startseite.',
            'default' => 'image',
            'attr' => 'data-mt-hero',
            'choices' => [
                'image' => 'Bild mit Text',
                'gradient' => 'Farbverlauf',
                'none' => 'Ohne',
            ],
        ],
        'hero_height' => [
            'key' => 'mt-hero-height',
            'group' => 'hero',
            'type' => 'select',
            'mode' => 'expert',
            'label' => 'Hero-Höhe',
            'help' => '',
            'default' => 'medium',
            'attr' => 'data-mt-hero-height',
            'choices' => [
                'small' => 'Niedrig',
                'medium' => 'Mittel',
                'large' => 'Hoch',
            ],
        ],
        'hero_title' => [
            'key' => 'mt-hero-title',
            'group' => 'hero',
            'type' => 'text',
            'mode' => 'simple',
            'label' => 'Überschrift',
            'help' => '',
            'default' => 'Willkommen in unserem Shop',
        ],
        'hero_text' => [
            'key' => 'mt-hero-text',
            'group' => 'hero',
            'type' => 'text',
            'mode' => 'simple',
            'label' => 'Text',
            'help' => '',
            'default' => '',
        ],
        'hero_cta_label' => [
            'key' => 'mt-hero-cta-label',
            'group' => 'hero',
            'type' => 'text',
            'mode' => 'simple',
            'label' => 'Button-Beschriftung',
            'help' => '',
            'default' => 'Jetzt entdecken',
        ],
        'hero_cta_url' => [
            'key' => 'mt-hero-cta-url',
            'group' => 'hero',
            'type' => 'text',
            'mode' => 'simple',
            'label' => 'Button-Ziel (Adresse)',
            'help' => 'Interne Adresse wie /neuheiten oder vollständige Adresse.',
            'default' => '/',
        ],
        'hero_image' => [
            'key' => 'mt-hero-image',
            'group' => 'hero',
            'type' => 'media',
            'mode' => 'simple',
            'label' => 'Hero-Bild',
            'help' => 'Eigenes Bild verwenden, keine Stockfotos ohne Lizenz.',
            'default' => '',
        ],
        'listing_layout' => [
            'key' => 'mt-listing-layout',
            'group' => 'listing',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Produktliste',
            'help' => 'Darstellung in Kategorien und Suche.',
            'default' => 'grid',
            'attr' => 'data-mt-listing',
            'choices' => [
                'grid' => 'Raster',
                'large' => 'Große Bilder',
                'list' => 'Liste',
            ],
        ],
        'listing_columns' => [
            'key' => 'mt-listing-columns',
            'group' => 'listing',
            'type' => 'range',
            'mode' => 'simple',
            'label' => 'Spalten auf dem Desktop',
            'help' => '',
            'default' => 4,
            'css' => '--mt-listing-cols',
            'min' => 2,
            'max' => 5,
            'step' => 1,
        ],
        'listing_ratio' => [
            'key' => 'mt-listing-ratio',
            'group' => 'listing',
            'type' => 'select',
            'mode' => 'expert',
            'label' => 'Bildformat',
            'help' => '',
            'default' => 'square',
            'attr' => 'data-mt-ratio',
            'choices' => [
                'square' => 'Quadrat (1:1)',
                'portrait' => 'Hochformat (4:5)',
                'landscape' => 'Querformat (4:3)',
            ],
        ],
        'listing_hover' => [
            'key' => 'mt-listing-hover',
            'group' => 'listing',
            'type' => 'select',
            'mode' => 'expert',
            'label' => 'Effekt beim Darüberfahren',
            'help' => '',
            'default' => 'zoom',
            'attr' => 'data-mt-hover',
            'choices' => [
                'none' => 'Keiner',
                'zoom' => 'Zoom',
                'second' => 'Zweites Bild',
            ],
        ],
        'listing_badges' => [
            'key' => 'mt-listing-badges',
            'group' => 'listing',
            'type' => 'toggle',
            'mode' => 'simple',
            'label' => 'Sonderpreis- und Neu-Siegel zeigen',
            'help' => '',
            'default' => true,
            'attr' => 'data-mt-badges',
        ],
        'listing_filter' => [
            'key' => 'mt-listing-filter',
            'group' => 'listing',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Filter',
            'help' => '',
            'default' => 'sidebar',
            'attr' => 'data-mt-filter',
            'choices' => [
                'sidebar' => 'Seitenleiste',
                'top' => 'Oben',
            ],
        ],
        'detail_layout' => [
            'key' => 'mt-detail-layout',
            'group' => 'detail',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Artikelseite',
            'help' => '',
            'default' => 'classic',
            'attr' => 'data-mt-detail',
            'choices' => [
                'classic' => 'Klassisch (Galerie links)',
                'stacked' => 'Untereinander',
                'sticky' => 'Kaufbox bleibt sichtbar',
            ],
        ],
        'detail_gallery' => [
            'key' => 'mt-detail-gallery',
            'group' => 'detail',
            'type' => 'select',
            'mode' => 'expert',
            'label' => 'Galerie',
            'help' => '',
            'default' => 'thumbs-bottom',
            'attr' => 'data-mt-gallery',
            'choices' => [
                'thumbs-bottom' => 'Vorschau unten',
                'thumbs-left' => 'Vorschau links',
                'dots' => 'Punkte',
            ],
        ],
        'detail_sticky_cart' => [
            'key' => 'mt-detail-sticky-cart',
            'group' => 'detail',
            'type' => 'toggle',
            'mode' => 'simple',
            'label' => 'Fixierter Warenkorb-Button auf dem Handy',
            'help' => '',
            'default' => true,
            'attr' => 'data-mt-sticky-cart',
        ],
        'detail_tabs' => [
            'key' => 'mt-detail-tabs',
            'group' => 'detail',
            'type' => 'select',
            'mode' => 'expert',
            'label' => 'Beschreibung',
            'help' => '',
            'default' => 'tabs',
            'attr' => 'data-mt-tabs',
            'choices' => [
                'tabs' => 'Reiter',
                'accordion' => 'Aufklappbar',
            ],
        ],
        'legal_price_note' => [
            'key' => 'mt-legal-price-note',
            'group' => 'legal',
            'type' => 'text',
            'mode' => 'simple',
            'label' => 'Hinweis neben dem Preis',
            'help' => 'Pflichtangabe nach PAngV. Der Link zu den Versandkosten bleibt immer erhalten.',
            'default' => 'inkl. MwSt., zzgl. Versand',
        ],
        'legal_unit_price' => [
            'key' => 'mt-legal-unit-price',
            'group' => 'legal',
            'type' => 'toggle',
            'mode' => 'simple',
            'label' => 'Grundpreis anzeigen',
            'help' => 'Pflicht, wo die Preisangabenverordnung einen Grundpreis verlangt.',
            'default' => true,
        ],
        'a11y_focus' => [
            'key' => 'mt-a11y-focus',
            'group' => 'a11y',
            'type' => 'select',
            'mode' => 'simple',
            'label' => 'Fokusrahmen',
            'help' => 'Sichtbarer Rahmen bei Tastaturbedienung.',
            'default' => 'standard',
            'attr' => 'data-mt-focus',
            'choices' => [
                'standard' => 'Standard',
                'strong' => 'Kräftig',
            ],
        ],
        'a11y_text_widget' => [
            'key' => 'mt-a11y-text-widget',
            'group' => 'a11y',
            'type' => 'toggle',
            'mode' => 'expert',
            'label' => 'Textgrößen-Schalter anzeigen',
            'help' => '',
            'default' => false,
        ],
        'perf_lazy' => [
            'key' => 'mt-perf-lazy',
            'group' => 'performance',
            'type' => 'toggle',
            'mode' => 'expert',
            'label' => 'Bilder erst beim Scrollen laden',
            'help' => '',
            'default' => true,
        ],
        'perf_preload_fonts' => [
            'key' => 'mt-perf-preload-fonts',
            'group' => 'performance',
            'type' => 'toggle',
            'mode' => 'expert',
            'label' => 'Haupt-Schrift vorladen',
            'help' => '',
            'default' => true,
        ],
        'custom_css' => [
            'key' => 'mt-custom-css',
            'group' => 'advanced',
            'type' => 'code',
            'mode' => 'expert',
            'label' => 'Eigenes CSS',
            'help' => 'Verfügbar mit dem Pro-Modul Eigener Code.',
            'default' => '',
            'pro' => 'custom-code',
            'language' => 'css',
        ],
        'custom_js' => [
            'key' => 'mt-custom-js',
            'group' => 'advanced',
            'type' => 'code',
            'mode' => 'expert',
            'label' => 'Eigenes JavaScript',
            'help' => 'Verfügbar mit dem Pro-Modul Eigener Code. Externe Skripte brauchen ggf. Einwilligung.',
            'default' => '',
            'pro' => 'custom-code',
            'language' => 'js',
        ],
    ],
];
